#server:
#  port: 8080
#spring:
#  application:
#    name: mybadis-demo-8080
server:
  port: 8005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: qyl728728
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: mybadis-demo-8080
#  templatemode:
#    query:
#      ordersByUserId: SELECT * FROM orders WHERE user_id = 1